name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Publish to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get release version
        id: get_version
        uses: battila7/get-version-action@v2

      - run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}
      - run: docker build -t rinha .
      - run: docker tag rinha williamsumida/rinha-backend-2024-q1:latest
      - run: docker push williamsumida/rinha-backend-2024-q1:latest
